source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'UrbanEaterRestaurant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UrbanEaterRestaurant
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SDWebImage/WebP'
  pod 'SwiftyJSON'
  pod 'SwiftMessages', '~> 5.0.1'
  pod 'MMMaterialDesignSpinner'
  pod 'IQKeyboardManagerSwift'
  pod 'EZSwiftExtensions'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'PopOverMenu'
  pod 'Socket.IO-Client-Swift', '~> 13.2.0'
  pod 'Starscream', '<= 3.0.5'
   
end
