# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UrbanEaterRestaurant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UrbanEaterRestaurant
  pod 'Alamofire'
  pod 'ReachabilitySwift'
  pod 'Google'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SDWebImage/WebP'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'MMMaterialDesignSpinner'
  #pod 'HTHorizontalSelectionList', '~> 0.7.4'
  pod 'IQKeyboardManagerSwift'
  pod 'EZSwiftExtensions'

end
